Find Free Time Function, and Google Tasks Service
ac-i2i-engineering/TimeSpace-AI pull request #18
Opened 2024-10-25 02:10 UTC by agrawal-prakhar

Fully developed and tested the find_times function which finds and returns all available time slots on a specific date for the given duration, excluding busy periods, from a given start time (in milltary hours) to end time.

Also, implemented the Google Tasks service, which can be used to retrieve the Google Tasks that we will be using with our Gcal API.
 
PS: When running it first time, you may need to delete the token.json file and re-run it to give it the required permissions, which I have enabled.

2024-10-25 18:17 UTC, AidenTag commented on API/gcal_scraper.py
> +        Helper function to parse time blocks and return a list of start and end times in datetime format.
These comments resemble the "gemini function calling" specifications here: https://ai.google.dev/gemini-api/docs/function-calling/tutorial?_gl=1*k6ewo8*_up*MQ..&gclid=CjwKCAjw1NK4BhAwEiwAVUHPUAnM2lEh2MUMQBP36SK8b49J17v-ZBhbJvYX73c9NiYq02GX2-ggRxoCn8QQAvD_BwE&lang=python
Was this the intention??? @agrawal-prakhar

2024-10-25 18:18 UTC, AidenTag commented on API/gcal_scraper.py
> +        Helper function to parse time blocks and return a list of start and end times in datetime format.
Otherwise I'm not sure if we need that much detail but it's definitely no problem for now.

2024-10-25 18:24 UTC, AidenTag commented on API/gcal_scraper.py
> +        print()
Not an issue, great work overall, just wanted to raise this. What is the intention for each of these functions? (I think we should be highly deliberate about answering this question not just here but going forward in the project, and I think we should lay out a more detailed game plan) 
Because I think although it is good to make deterministic functions, AI would be pretty good at most of this. Was the intention of implementing them outright just to make it better than pretty good? Also are these functions intended to be called by the AI? How? And in what use case? And how exactly would the flow look? Not criticizing the work at all, looks good, just wanted to be extra clear about this so we're all on the same page working as congruently as possible. @agrawal-prakhar

2024-10-25 20:28 UTC, AidenTag commented on API/google_tasks_service.py
We need more parity between this and gcal_service. I will raise issue. The main issue that methods in gcal_service aren't there/got deleted. I don't know when this happened.

2024-10-26 02:57 UTC, DhyeyMavani2003 commented on API/google_tasks_service.py
Yes, we have gotten rid of them @AidenTag since the gcal service should only do authentication and user management. To align with industry best practices, we separated the rest of the logic out to other respective classes in liam's PR we merged earlier!

2024-10-26 03:06 UTC, DhyeyMavani2003 commented on API/gcal_scraper.py
> +        Helper function to parse time blocks and return a list of start and end times in datetime format.
Yes, this is intentional @AidenTag and from now on we will try to document as much of the code as we can. Our Technical Product Manager will be consuming the code structure and draft various pieces of documentation for us!

2024-10-26 03:08 UTC, AidenTag commented on API/google_tasks_service.py
@DhyeyMavani2003 Then why are they in google tasks service?? I wasn't saying necessarily that I think that gcal_serivce should have them I was merely that there shouldn't be a difference between the two. A-ok with taking them from the tasks service as well, (though it might be the case that @agrawal-prakhar put them there just temporarily until the functionality is put in the right places).

2024-10-26 03:20 UTC, DhyeyMavani2003 requested changes
Great work @agrawal-prakhar and thanks for sharing your thoughts as well @AidenTag!
I just did an initial pass through this, added some suggestions, and responded to some vital points. Hope this helps! 

Looking forward to the future iteration of this PR containing more clear division of labor between `deterministic` and `LLM API call` paradigms!

2024-10-26 03:20 UTC, DhyeyMavani2003 commented on API/gcal_scraper.py
> +        #Return the formatted free times
```suggestion
        # Return the formatted free times
```

2024-10-26 03:20 UTC, DhyeyMavani2003 commented on API/gcal_scraper.py
> +        print()
Great point @AidenTag, was about to discuss this in the next meeting. Based on my industry experience, I think the problem with LLM hallucination is real. Although we might be able to circumvent it through prompt engineering to a level of 80% (max), it still cannot beat the deterministic functions in terms of handling well defined algorithmic tasks.

We will definitely utilise AI (LLM API calls), but it makes sense to use it for only very specific use-cases such as:
- solving vague problems
- providing agentic orchestration / interface between vague user queries and internally implemented API calls!

It's good that we have both sorts of functions for now, we can test them over coming days, make some design decisions, implement rest of the methods, and some of us should move forward with integration using FastAPI + figuring out the frontend / login piece!

Great efforts so far @AidenTag @agrawal-prakhar @liamjdavis!

2024-10-26 03:20 UTC, DhyeyMavani2003 commented on API/google_tasks_service.py
> +import os.path
This seems to be an redundant repetition of `gcal_service.py`, hence I recommend getting rid of this file and using the functionality established elsewhere to get dependent methods working! @agrawal-prakhar @liamjdavis @AidenTag

2024-10-26 16:39 UTC, AidenTag commented on API/gcal_scraper.py
> +        print()
Sounds good. I was more saying that we should be more intentional with all of this stuff. Because looking at it right now I'm not sure how everything fits cohesively into the overall vision. And ideally we should be making engineering plans and delegating work so that everything is thought through before we do it. @DhyeyMavani2003 @agrawal-prakhar

2024-10-26 16:47 UTC, AidenTag commented on API/google_tasks_service.py
> +import os.path
@DhyeyMavani2003 what do you mean when by "functionality established elsewhere" and "dependent methods"?
I agree that we are doing much of the same auth flow and it should be consolidated, i.e. just declare SCOPES to have tasks and calendar, and then build a separate calendar_service and tasks_service for this class. So then it should just be google_service.

2024-10-26 22:09 UTC, DhyeyMavani2003 commented on API/gcal_scraper.py
> +        print()
Yes, I was about to give more directed engineering plan after your meeting with Alex. And, yes, I have been busy with other commitments recently, so this had slowed down the direct guidance especially due to new hires. @AidenTag @agrawal-prakhar we will pin down things more once we have some sort of tech stack working, and I think we are at that point now. Looking forward to your doc & discussion notes from Alex!

2024-10-26 22:11 UTC, DhyeyMavani2003 commented on API/google_tasks_service.py
Yes @AidenTag @agrawal-prakhar as I told you before, the gcal_service already has them, I don't know why we have this duplication of functionality in Prakhar's branch! We will definitely get rid of it, when incorporating it to our code in the current main branch!

2024-10-26 22:13 UTC, DhyeyMavani2003 commented on API/google_tasks_service.py
> +import os.path
yes, all of this depends on how we want to do the OAuth or the like. I am waiting on you @AidenTag to present your research on potential authentication methods we can use at the moment since that will help pin down.

2024-10-26 22:23 UTC, agrawal-prakhar commented on API/google_tasks_service.py
> +import os.path
Yes, that's a good point! My initial idea was to have it as a separate class so to keep the Google Task service more modularized as it is a different API call. However, it does still use google auth and other similar services, so we can get rid of it and get the functionality established in a google_service class itself.

2024-10-26 22:26 UTC, agrawal-prakhar commented
> Great work @agrawal-prakhar and thanks for sharing your thoughts as well @AidenTag! I just did an initial pass through this, added some suggestions, and responded to some vital points. Hope this helps!
> 
> Looking forward to the future iteration of this PR containing more clear division of labor between `deterministic` and `LLM API call` paradigms!

Sure, This PR is still mainly deterministic, and the idea is to now use the LLM API calls to use these deterministic functionalities established as the next step.

2024-10-30 19:34 UTC, DhyeyMavani2003 approved these changes
LGTM! Although we have pivoted, this looks great now! Thanks for great work @agrawal-prakhar!

2024-10-30 19:34 UTC, merged